### ISSUE TITLE
Aspect Ratio

### ISSUE THREAD

**Issue by shersoni610** [branislavhesko/segment-anything-ui#1]
Hello,
How can i maintain the aspect ratio of the input image in the main window?

**Comment by shersoni610** [comment]
Hello,

Is is possible to adjust the left and right panels ( to make smaller ) and the main window larger?

**Comment by branislavhesko** [comment]
Hi, I will inspect this option, it would be better if aspect ratio can be maintained. Otherwise, to adjust left right panel size is to set higher image size in config.

I will try to improve this behavior in the future.

**Comment by branislavhesko** [comment]
Now you can change image shape to a rectangular: left and right panel will adjust to it. Sorry for the delay @shersoni610 .
