### ISSUE TITLE
Error loading model: name 'create_sam_model' is not defined

### ISSUE THREAD

**Issue by lzhangsh** [branislavhesko/segment-anything-ui#10]
Thanks for making this project practical, but I did have a few questions while installing it and would like to get your assistance :)
I have followed every step listed in the Readme. I thought the prerequisite _**_efficientvit_**_ installation worked, since I got these feedbacks:
![86e4bf2f8c2fa156187d72ff3d58059a](https://github.com/user-attachments/assets/87d6b0d3-d43f-48e6-87fd-24e246406cef)
![16de43b7698773854803dfe7ff1c7a4a](https://github.com/user-attachments/assets/4fa1538e-1bff-4c69-b8f9-2e8d0d0553c8)
However, when I ran python segment-anything-ui/main_window.py, it failed and had error saying  _'create_sam_model' is not defined_
![image](https://github.com/user-attachments/assets/d1fdf366-ba2d-4b2f-a041-4e26437162f2)

**Comment by branislavhesko** [comment]
I will check this problem in upcoming days. I think I messed up optional efficientvit model imports.

**Comment by ChiuLongHim** [comment]
I am facing the same problem currently, is there any update on this?

**Comment by branislavhesko** [comment]
@ChiuLongHim  @lzhangsh 

I fixed the error, efficientvit slightly changed its api and I forgot to include my variable about efficientvit presence.
If you install it according to README.md (and even if you don't), it should work.

Sorry, I don't have much of a free time right now.

Branislav
