### ISSUE TITLE
questions on some features and functions

### ISSUE THREAD

**Issue by chqzeng** [branislavhesko/segment-anything-ui#3]
Hi thanks you for working this great project, it is lightweight but quite powerful, thank you!

I just set it up and do some test, I have a few questions : 

- parameters. currently there are many parameters provided on the left side, could you provide some explanation on those parameters? I try to use the "Add Point" tool to create some mask, but I notice the result is different from the facebook page: https://segment-anything.com/demo.   is it possible for me to generate same mask as that site with a specific set of parameters?

- "Remove Hidden Mask": what do you mean by that? not all the mask are showing?  which is showing and which is not?  I notice sometimes when I draw a box to create mask, it will show some random masks from background, which I don't know where those mask comes from.

- the shortcut keys. sometimes the keys work , sometimes not. For instance,  sometimes when I click a "W", it won't start Add point mode.

- for the button: "Manual Polygon | Draw polygon with mouse" ,, when I draw a polygon , it only show the outline, but it is not filled ? how this can be further convert to an mask patch as a filled polygon? I tried to export such polygon as annotation, the output mask seems have this polygon, but the location is incorrect. 

- is it possible to zoom in and out the image? I notice sometimes I need to zoom in to select very small object

- what is your plan on  "Show Image /Show Visualization "?  it would be great if I can use these two buttons to shore the raw input image, and show the annotations, to hide/show annotations fast and see whether the annotation is accurate.

Best, 
Chui,

**Comment by Nomination-NRB** [comment]
> Hi thanks you for working this great project, it is lightweight but quite powerful, thank you!
> 
> I just set it up and do some test, I have a few questions :
> 
> * parameters. currently there are many parameters provided on the left side, could you provide some explanation on those parameters? I try to use the "Add Point" tool to create some mask, but I notice the result is different from the facebook page: https://segment-anything.com/demo.   is it possible for me to generate same mask as that site with a specific set of parameters?
> * "Remove Hidden Mask": what do you mean by that? not all the mask are showing?  which is showing and which is not?  I notice sometimes when I draw a box to create mask, it will show some random masks from background, which I don't know where those mask comes from.
> * the shortcut keys. sometimes the keys work , sometimes not. For instance,  sometimes when I click a "W", it won't start Add point mode.
> * for the button: "Manual Polygon | Draw polygon with mouse" ,, when I draw a polygon , it only show the outline, but it is not filled ? how this can be further convert to an mask patch as a filled polygon? I tried to export such polygon as annotation, the output mask seems have this polygon, but the location is incorrect.
> * is it possible to zoom in and out the image? I notice sometimes I need to zoom in to select very small object
> * what is your plan on  "Show Image /Show Visualization "?  it would be great if I can use these two buttons to shore the raw input image, and show the annotations, to hide/show annotations fast and see whether the annotation is accurate.
> 
> Best, Chui,

Hello, I have read your question and think my current warehouse can meet your needs (if possible, please support the author of the original warehouse).
This is link: https://github.com/Nomination-NRB/SAM-webui

**Comment by branislavhesko** [comment]
> Hi thanks you for working this great project, it is lightweight but quite powerful, thank you!
> 
> I just set it up and do some test, I have a few questions :
> 
> * parameters. currently there are many parameters provided on the left side, could you provide some explanation on those parameters? I try to use the "Add Point" tool to create some mask, but I notice the result is different from the facebook page: https://segment-anything.com/demo.   is it possible for me to generate same mask as that site with a specific set of parameters?
> * "Remove Hidden Mask": what do you mean by that? not all the mask are showing?  which is showing and which is not?  I notice sometimes when I draw a box to create mask, it will show some random masks from background, which I don't know where those mask comes from.
> * the shortcut keys. sometimes the keys work , sometimes not. For instance,  sometimes when I click a "W", it won't start Add point mode.
> * for the button: "Manual Polygon | Draw polygon with mouse" ,, when I draw a polygon , it only show the outline, but it is not filled ? how this can be further convert to an mask patch as a filled polygon? I tried to export such polygon as annotation, the output mask seems have this polygon, but the location is incorrect.
> * is it possible to zoom in and out the image? I notice sometimes I need to zoom in to select very small object
> * what is your plan on  "Show Image /Show Visualization "?  it would be great if I can use these two buttons to shore the raw input image, and show the annotations, to hide/show annotations fast and see whether the annotation is accurate.
> 
> Best, Chui,

Hello, sorry for late response.

I will need to definitely prepare a better README for explaining buttons and their functionality.  Thank you for your feedback, it is really worth improving documentation.

Regarding zooming capabilities. I think this may be the next feature, but don't expect it in the near term, currently I don't have much free time. 

Anyway, thank you for the feedback, I hope I will improve this repository in the future.
Cheers, Braňo
