### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by m23project** [branislavhesko/segment-anything-ui#4]
Hi,

thanks for your work :-)

I managed to install your software, but to run it, I had to install (on Debian 12) in addition

`pip3 install torchvision`

it seems to be missing in the requirements.txt.

Then I needed to install system packages with

`apt install libxkbcommon-x11-0 qt5dxcb-plugin libxcb-cursor0`

to fix the Qt error when running

`python segment_anything_ui/main_window.py`

**Comment by branislavhesko** [comment]
Thank you for your feedback, I appreciate it!

Your fixes added to README.md and requirements.txt
