### ISSUE TITLE
where is default_path variable?

### ISSUE THREAD

**Issue by Shigeto-Amatake** [branislavhesko/segment-anything-ui#5]
I could not find in config.py.

**Comment by benibargera** [comment]
Hi Branislav. I'm a bit confused about that as well. As well as what value we're supposed to put in there? I'd really like to use your app :) Thanks in advance!

**Comment by branislavhesko** [comment]
Hello.
If you think default checkpoint for SAM path, it is called from here:
https://github.com/branislavhesko/segment-anything-ui/blob/496bef9ac7571edd9080def9816a8efc1f882093/segment_anything_ui/config.py#L35
